### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by bigtrapmoneyman420** [CycloneAddons/instagram.js#1]
i get npm i command not found? why?

**Comment by iamglimpse2** [comment]
> i get npm i command not found? why?

What do u mean ?

**Comment by CycloneAddons** [comment]
Sorry I am Unable To Understand Can U Explain Me What Problem U R facing ???

**Comment by bigtrapmoneyman420** [comment]
npm i command not found how fix this sorry am new to this instagram hackig stuff

**Comment by CycloneAddons** [comment]
> npm i command not found how fix this sorry am new to this instagram hackig stuff

First Of All This Is Not Hacking Tool. This Is Simple Package Which Interect With Instagram-private-api You Can Use This For Create A Bot Like Discord 

And Please Learn Nodejs for it
